### ISSUE TITLE
Crash in modpack resolved by removing Eidolon

### ISSUE THREAD

**Issue by Syogren** [Alexthw46/Eidolon-Repraised#34]
A friend and I are making a modpack that we included Eidolon-Repraised in, and upon being in a village it would crash.  This was resolved by removing the mod from the pack, so perhaps the crash issue is related to villages or some kind of mod conflict?

Here's the crash report:

[message 2023 12 17 1.txt](https://github.com/Alexthw46/Eidolon-Repraised/files/13698719/message.2023.12.17.1.txt)

**Comment by SiverDX** [comment]
The only thing I could imagine triggering that error are these

https://github.com/Alexthw46/Eidolon-Repraised/blob/8c862e755fd42cd7b7717c0a8f530f6d88ee373f/src/main/java/elucent/eidolon/common/ritual/RepellingRitual.java#L48

https://github.com/Alexthw46/Eidolon-Repraised/blob/8c862e755fd42cd7b7717c0a8f530f6d88ee373f/src/main/java/elucent/eidolon/common/ritual/AllureRitual.java#L41

But this crash happened due to a Villager which would not be targeted by either (and do priests even perform rituals?)
(You would also need some sort of multi-threading for this to occur)

So either a goal got removed in a network thread or sth. like that or a some mod added a null entry to the goal selectors
Don't think Eidolon does either of those

**Comment by Alexthw46** [comment]
A ritual can only be made by a player, with the brazier, so can't be that.
The only thing that targets villager AI is that a new goal for giving the holy sign is added when the villager is spawned. Another mod clash with this for some reason, as the mod on its own doesn't

**Comment by Alexthw46** [comment]
A priority change was done for the villager ai injection, another mod was likely adding and then removing goals without checking or smth. Hopefully that solves it...
