### ISSUE TITLE
Incompatible with Cofh Core mod,Archangel's Sight will not work.

### ISSUE THREAD

**Issue by 6371peter** [Alexthw46/Eidolon-Repraised#42]
AngelSightItem use ArrowLooseEvent,but Cofh Core(ArcheryEvents.java) set this event canceled.

**Comment by SiverDX** [comment]
For reference:

https://github.com/CoFH/CoFHCore/blob/62908ffc3e041ed204b20f98c15334fe1d0dbbe3/src/main/java/cofh/core/event/ArcheryEvents.java#L37-L46

https://github.com/CoFH/CoFHCore/blob/62908ffc3e041ed204b20f98c15334fe1d0dbbe3/src/main/java/cofh/core/util/helpers/ArcheryHelper.java#L72

TL;DR:
They break the entire event because why not
(It default cancels and the actual shooting logic then happens in their own code)

**Comment by SiverDX** [comment]
to be fair the eidolon implementation is equally problematic 

listen to entity join level, if it's a projectile check owner and add the mode 

might even be other, better ways
