### ISSUE TITLE
Release 0.3.8.11 incompatable with Helion's Sniffer+

### ISSUE THREAD

**Issue by KajesLorian** [Alexthw46/Eidolon-Repraised#71]
Initially upgraded from 0.3.8.9 straight to 0.3.8.9.11
Game crashes during launch with following crash:
https://pastebin.com/WY8gwGys

Checked 0.3.8.10 and it works.

Minecraft 1.20.1
Neoforge 47.1.105
Helion's Sniffer+ 0.3.0

**Comment by Alexthw46** [comment]
Since the only thing that could matter in .11 is updating the apotheosis compat, check that you have the latest version aka post 7.4.0. Pretty sure that if the pre-breaking update version is used there is a cascade of error behind the scenes (even if weird, since 3.8.10 would crash with new apo with a proper err).

**Comment by KajesLorian** [comment]
That was indeed the issue, and updating Apotheosis fixed it. Thank you!
